from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('billing','0001_initial')]
    operations=[
        migrations.CreateModel(name='Invoice',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=50,unique=True)),('customer_name',models.CharField(max_length=200)),('invoice_date',models.DateField()),('due_date',models.DateField()),('currency',models.CharField(default='USD',max_length=3)),('subtotal',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('tax_rate',models.DecimalField(decimal_places=2,default=0,max_digits=6)),('tax_amount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('status',models.CharField(choices=[('DRAFT','Draft'),('ISSUED','Issued'),('SENT','Sent'),('PARTIAL','Partially Paid'),('PAID','Paid'),('VOID','Void')],default='DRAFT',max_length=20)),('notes',models.TextField(blank=True)),('odoo_invoice_id',models.IntegerField(blank=True,null=True,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('project',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='invoices',to='projects.project'))]),
        migrations.CreateModel(name='InvoiceLine',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('description',models.CharField(max_length=500)),('quantity',models.DecimalField(decimal_places=2,max_digits=10)),('unit_price',models.DecimalField(decimal_places=2,max_digits=12)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('billable_source',models.CharField(default='MANUAL',max_length=30)),('invoice',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='lines',to='billing.invoice')),('phase',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='projects.phase'))]),
        migrations.CreateModel(name='InvoicePayment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('payment_date',models.DateField()),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('reference',models.CharField(blank=True,max_length=200)),('odoo_payment_id',models.IntegerField(blank=True,null=True,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('invoice',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payments',to='billing.invoice'))]),
    ]
